### ISSUE TITLE
Active Tab Style

### ISSUE THREAD

**Issue by martineboh** [MostafaRostami72/react-best-tabs#1]
Thanks for creating this amazing component! How do I apply style to the active tab title background? I have tried doing that with no success apart from editing the css directly

**Comment by MostafaRostami72** [comment]
Hi
Unfortunately, prop is not considered for isActive mode.

You can add a custom className to the <Tab> component and style it in sass. Like the example below

`
    <Tab title="tab 3" className="some-class">
                ...
            </Tab>
`

// in sass


.some-class {
    ...

    &.active {
        ...
    }
}

**Comment by martineboh** [comment]
Adding a custom `className` to the component did the trick. Thanks
