### ISSUE TITLE
Sticky Tabs

### ISSUE THREAD

**Issue by martineboh** [MostafaRostami72/react-best-tabs#2]
Thanks for this wonderful package.
I have a requirement to make the Tab header sticky and the content scrollable when the page is scrolled.
How do I achieve this with your pckage?

**Comment by MostafaRostami72** [comment]
Hello
Sorry for the delay 
You can add the following values to class .rb-tabs-header

.rb-tabs-header {
...
    position: sticky;
    top: 0;
....
}
